apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment  # cluster deployment name for app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1 # deployment selector label for app2. It should match the label names in the template
  template:
    metadata:
      labels:
        app: app1 # pod label creator for app2. It should match the deployment selector label.
    spec:
      containers:
        - name: app1
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from App 1"
          ports:
            - containerPort: 5678

---

apiVersion: v1
kind: Service
metadata:
  name: app1-service  # cluster service name for app2
spec:
  selector:
    app: app1 # Service selector label. Must match Deployment .spec.template.metadata.labels and .spec.selector.matchLabels
  ports:
    - port: 80
      targetPort: 5678