apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment  # cluster deployment name for app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3 # deployment selector label for app2. It should match the label names in the template
  template:
    metadata:
      labels:
        app: app3 # pod label creator for app2. It should match the deployment selector label.
    spec:
      containers:
        - name: app3
          image: paulbouwer/hello-kubernetes:1.10
          env:
            - name: MESSAGE
              value: "Hello from App 3"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app3-service  # cluster service name for app2
spec:
  type: ClusterIP #default
  selector:
    app: app3 # Service selector label. Must match Deployment .spec.template.metadata.labels and .spec.selector.matchLabels
  ports:
    - port: 80
      targetPort: 8080